# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-10-12 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonHolding',
            fields=[
                ('year', models.IntegerField(blank=True, null=True)),
                ('isin', models.CharField(blank=True, max_length=20, null=True)),
                ('holdings', models.CharField(blank=True, max_length=12, null=True)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sector', models.CharField(blank=True, max_length=26, null=True)),
                ('security_type', models.CharField(blank=True, max_length=20, null=True)),
                ('country_noformatting', models.CharField(blank=True, max_length=34, null=True)),
                ('price', models.CharField(blank=True, max_length=8, null=True)),
                ('broad_market', models.CharField(blank=True, db_column='broad market', max_length=17, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('ticker', models.CharField(blank=True, max_length=20, null=True)),
                ('ticker_sector', models.CharField(blank=True, max_length=24, null=True)),
                ('manager', models.CharField(blank=True, max_length=9, null=True)),
                ('market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('category', models.CharField(blank=True, max_length=13, null=True)),
                ('country', models.CharField(blank=True, max_length=34, null=True)),
            ],
            options={
                'db_table': 'carbon_holding',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarbonMsci',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('issuerid', models.CharField(blank=True, max_length=18, null=True)),
                ('isin', models.CharField(blank=True, max_length=12, null=True)),
                ('issuer', models.CharField(blank=True, max_length=88, null=True)),
                ('issuer_market_cap', models.CharField(blank=True, max_length=19, null=True)),
                ('carbon_emissions', models.CharField(blank=True, max_length=13, null=True)),
            ],
            options={
                'db_table': 'carbon_msci',
                'managed': False,
            },
        ),
    ]
